"""initial

Revision ID: 112477f6c822
Revises: 
Create Date: 2022-06-03 08:53:25.259908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112477f6c822'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listmenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('timing', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listmenu')
    # ### end Alembic commands ###
